import type { AppState } from "./types";

const SESSION_JAN_2026 = "session-2026-01";

export const sampleData: AppState = {
  sessions: [
    {
      id: SESSION_JAN_2026,
      year: 2026,
      month: 1,
      label: "Winter",
      status: "trending",
    },
    {
      id: "session-2025-12",
      year: 2025,
      month: 12,
      label: "Holiday",
      status: "in-progress",
    },
    {
      id: "session-2025-11",
      year: 2025,
      month: 11,
      label: "Fall Classic",
      status: "in-progress",
    },
    {
      id: "session-2025-10",
      year: 2025,
      month: 10,
      label: "October Skills",
      status: "completed",
    },
    {
      id: "session-2025-09",
      year: 2025,
      month: 9,
      label: "Back to School",
      status: "completed",
    },
    {
      id: "session-2025-08",
      year: 2025,
      month: 8,
      label: "Summer Wrap",
      status: "completed",
    },
    {
      id: "session-2025-07",
      year: 2025,
      month: 7,
      label: "July Camp",
      status: "completed",
    },
  ],
  players: [
    {
      id: "player-1",
      name: "Alex Johnson",
      email: "alex.johnson@example.com",
      grade: "3",
      level: "beginner",
      sessionIds: [SESSION_JAN_2026],
    },
    {
      id: "player-2",
      name: "Brianna Lee",
      email: "brianna.lee@example.com",
      grade: "4",
      level: "intermediate",
      sessionIds: [SESSION_JAN_2026],
    },
    {
      id: "player-3",
      name: "Carlos Mendez",
      email: "carlos.mendez@example.com",
      grade: "5",
      level: "advanced",
      sessionIds: [SESSION_JAN_2026],
    },
    {
      id: "player-4",
      name: "Diana Park",
      email: "diana.park@example.com",
      grade: "3",
      level: "beginner",
      sessionIds: [SESSION_JAN_2026],
    },
    {
      id: "player-5",
      name: "Ethan Brooks",
      email: "ethan.brooks@example.com",
      grade: "6",
      level: "intermediate",
      sessionIds: [SESSION_JAN_2026],
    },
    {
      id: "player-6",
      name: "Fatima Ali",
      email: "fatima.ali@example.com",
      grade: "4",
      level: "beginner",
      sessionIds: [SESSION_JAN_2026],
    },
    {
      id: "player-7",
      name: "Grace Turner",
      email: "grace.turner@example.com",
      grade: "5",
      level: "intermediate",
      sessionIds: [SESSION_JAN_2026],
    },
    {
      id: "player-8",
      name: "Henry Kim",
      email: "henry.kim@example.com",
      grade: "7",
      level: "advanced",
      sessionIds: [SESSION_JAN_2026],
    },
    {
      id: "player-9",
      name: "Isabella Rossi",
      email: "isabella.rossi@example.com",
      grade: "6",
      level: "beginner",
      sessionIds: [SESSION_JAN_2026],
    },
    {
      id: "player-10",
      name: "Jamal Wright",
      email: "jamal.wright@example.com",
      grade: "8",
      level: "intermediate",
      sessionIds: [SESSION_JAN_2026],
    },
  ],
};
