import type { AppState } from "./types";

const PROGRAM_SUMMER_2026 = "program-summer-2026";
const PROGRAM_WINTER_2026 = "program-winter-2026";
const PROGRAM_HOLIDAY_2025 = "program-holiday-2025";
const PROGRAM_FALL_2025 = "program-fall-2025";
const PROGRAM_OCTOBER_2025 = "program-october-2025";
const PROGRAM_BTS_2025 = "program-bts-2025";
const PROGRAM_SUMMER_WRAP_2025 = "program-summer-wrap-2025";
const PROGRAM_JULY_2025 = "program-july-2025";

const SESSION_JAN_2026 = "session-2026-01";

/** Deterministic demo profile photos for roster cards. */
function avatarFor(seed: string) {
  return `https://api.dicebear.com/9.x/adventurer/svg?seed=${encodeURIComponent(seed)}&size=80`;
}

/** Six weekly Summer Camp 2026 clinics spanning July–August. */
const SUMMER_2026_CLINICS = [
  { id: "clinic-summer-2026-w1", week: 1, month: 7, label: "Week 1" },
  { id: "clinic-summer-2026-w2", week: 2, month: 7, label: "Week 2" },
  { id: "clinic-summer-2026-w3", week: 3, month: 7, label: "Week 3" },
  { id: "clinic-summer-2026-w4", week: 4, month: 8, label: "Week 4" },
  { id: "clinic-summer-2026-w5", week: 5, month: 8, label: "Week 5" },
  { id: "clinic-summer-2026-w6", week: 6, month: 8, label: "Week 6" },
] as const;

export const sampleData: AppState = {
  programs: [
    {
      id: PROGRAM_SUMMER_2026,
      name: "Summer Camp 2026",
      year: 2026,
      status: "trending",
      open: true,
      startMonth: 7,
      endMonth: 8,
      location: "Weston, CT",
    },
    {
      id: PROGRAM_WINTER_2026,
      name: "Winter 2026",
      year: 2026,
      status: "trending",
      open: true,
      startMonth: 1,
      endMonth: 1,
      location: "Weston, CT",
    },
    {
      id: PROGRAM_HOLIDAY_2025,
      name: "Holiday 2025",
      year: 2025,
      status: "in-progress",
      open: true,
      startMonth: 12,
      endMonth: 12,
    },
    {
      id: PROGRAM_FALL_2025,
      name: "Fall Classic 2025",
      year: 2025,
      status: "in-progress",
      open: true,
      startMonth: 11,
      endMonth: 11,
    },
    {
      id: PROGRAM_OCTOBER_2025,
      name: "October Skills 2025",
      year: 2025,
      status: "completed",
      open: false,
      startMonth: 10,
      endMonth: 10,
    },
    {
      id: PROGRAM_BTS_2025,
      name: "Back to School 2025",
      year: 2025,
      status: "completed",
      open: false,
      startMonth: 9,
      endMonth: 9,
    },
    {
      id: PROGRAM_SUMMER_WRAP_2025,
      name: "Summer Wrap 2025",
      year: 2025,
      status: "completed",
      open: false,
      startMonth: 8,
      endMonth: 8,
    },
    {
      id: PROGRAM_JULY_2025,
      name: "July Camp 2025",
      year: 2025,
      status: "completed",
      open: false,
      startMonth: 7,
      endMonth: 7,
    },
  ],
  sessions: [
    ...SUMMER_2026_CLINICS.map((clinic) => ({
      id: clinic.id,
      programId: PROGRAM_SUMMER_2026,
      year: 2026,
      month: clinic.month,
      week: clinic.week,
      label: clinic.label,
      status: "trending" as const,
      available: clinic.week <= 4,
    })),
    {
      id: SESSION_JAN_2026,
      programId: PROGRAM_WINTER_2026,
      year: 2026,
      month: 1,
      label: "Winter",
      status: "trending",
      available: true,
    },
    {
      id: "session-2025-12",
      programId: PROGRAM_HOLIDAY_2025,
      year: 2025,
      month: 12,
      label: "Holiday",
      status: "in-progress",
      available: true,
    },
    {
      id: "session-2025-11",
      programId: PROGRAM_FALL_2025,
      year: 2025,
      month: 11,
      label: "Fall Classic",
      status: "in-progress",
      available: true,
    },
    {
      id: "session-2025-10",
      programId: PROGRAM_OCTOBER_2025,
      year: 2025,
      month: 10,
      label: "October Skills",
      status: "completed",
      available: false,
    },
    {
      id: "session-2025-09",
      programId: PROGRAM_BTS_2025,
      year: 2025,
      month: 9,
      label: "Back to School",
      status: "completed",
      available: false,
    },
    {
      id: "session-2025-08",
      programId: PROGRAM_SUMMER_WRAP_2025,
      year: 2025,
      month: 8,
      label: "Summer Wrap",
      status: "completed",
      available: false,
    },
    {
      id: "session-2025-07",
      programId: PROGRAM_JULY_2025,
      year: 2025,
      month: 7,
      label: "July Camp",
      status: "completed",
      available: false,
    },
  ],
  players: [
    {
      id: "player-1",
      name: "Alex Johnson",
      email: "alex.johnson@example.com",
      grade: "3",
      level: "beginner",
      programIds: [PROGRAM_WINTER_2026],
      sessionIds: [SESSION_JAN_2026],
      avatarUrl: avatarFor("alex-johnson"),
    },
    {
      id: "player-2",
      name: "Brianna Lee",
      email: "brianna.lee@example.com",
      grade: "4",
      level: "intermediate",
      programIds: [PROGRAM_WINTER_2026],
      sessionIds: [SESSION_JAN_2026],
      avatarUrl: avatarFor("brianna-lee"),
    },
    {
      id: "player-3",
      name: "Carlos Mendez",
      email: "carlos.mendez@example.com",
      grade: "5",
      level: "advanced",
      programIds: [PROGRAM_WINTER_2026],
      sessionIds: [SESSION_JAN_2026],
      avatarUrl: avatarFor("carlos-mendez"),
    },
    {
      id: "player-4",
      name: "Diana Park",
      email: "diana.park@example.com",
      grade: "3",
      level: "beginner",
      programIds: [PROGRAM_WINTER_2026],
      sessionIds: [SESSION_JAN_2026],
      avatarUrl: avatarFor("diana-park"),
    },
    {
      id: "player-5",
      name: "Ethan Brooks",
      email: "ethan.brooks@example.com",
      grade: "6",
      level: "intermediate",
      programIds: [PROGRAM_WINTER_2026],
      sessionIds: [SESSION_JAN_2026],
      avatarUrl: avatarFor("ethan-brooks"),
    },
    {
      id: "player-6",
      name: "Fatima Ali",
      email: "fatima.ali@example.com",
      grade: "4",
      level: "beginner",
      programIds: [PROGRAM_WINTER_2026],
      sessionIds: [SESSION_JAN_2026],
      avatarUrl: avatarFor("fatima-ali"),
    },
    {
      id: "player-7",
      name: "Grace Turner",
      email: "grace.turner@example.com",
      grade: "5",
      level: "intermediate",
      programIds: [PROGRAM_WINTER_2026],
      sessionIds: [SESSION_JAN_2026],
      avatarUrl: avatarFor("grace-turner"),
    },
    {
      id: "player-8",
      name: "Henry Kim",
      email: "henry.kim@example.com",
      grade: "7",
      level: "advanced",
      programIds: [PROGRAM_WINTER_2026],
      sessionIds: [SESSION_JAN_2026],
      avatarUrl: avatarFor("henry-kim"),
    },
    {
      id: "player-9",
      name: "Isabella Rossi",
      email: "isabella.rossi@example.com",
      grade: "6",
      level: "beginner",
      programIds: [PROGRAM_WINTER_2026],
      sessionIds: [SESSION_JAN_2026],
      avatarUrl: avatarFor("isabella-rossi"),
    },
    {
      id: "player-10",
      name: "Jamal Wright",
      email: "jamal.wright@example.com",
      grade: "8",
      level: "intermediate",
      programIds: [PROGRAM_WINTER_2026],
      sessionIds: [SESSION_JAN_2026],
      avatarUrl: avatarFor("jamal-wright"),
    },
    {
      id: "player-child-1",
      name: "Maya Rivera",
      email: "user@demo.com",
      grade: "5",
      level: "beginner",
      programIds: [],
      sessionIds: [],
      parentUserId: "user-1",
      avatarUrl: avatarFor("maya-rivera"),
    },
    {
      id: "player-child-2",
      name: "Lucas Rivera",
      email: "user@demo.com",
      grade: "7",
      level: "intermediate",
      programIds: [PROGRAM_HOLIDAY_2025],
      sessionIds: ["session-2025-12"],
      parentUserId: "user-1",
      paymentLinkSentAt: "2025-11-20T12:00:00.000Z",
      avatarUrl: avatarFor("lucas-rivera"),
    },
  ],
};
